export const experiences = [
  {
    id: 1,
    title: "Développeur – ReactJS & Symfony | Egerie Software",
    date: "Août 2022 - Juillet 2024",
    stack: [
      "ReactJS",
      "TypeScript",
      "Symfony",
      "API Platform",
      "Docker",
      "Git",
      "Cypress",
      "Jest",
      "PHPUnit",
      "Figma",
    ],
    missions: [
      "Développement d’un logiciel d’analyse des risques cyber en ReactJS et Symfony, permettant aux entreprises d’identifier et de gérer leurs vulnérabilités.",
      "Conception et développement d’une bibliothèque de composants réutilisables en ReactJS et TypeScript pour assurer une cohérence UI et accélérer le développement.",
      "Collaboration avec les équipes UX/UI sur Figma pour concevoir des interfaces utilisateur optimisées et accessibles.",
      "Automatisation des tests avec Cypress et Jest en front-end, et PHPUnit en back-end, garantissant une qualité de code robuste et scalable.",
      "Développement et maintenance de services backend en Symfony et API Platform en suivant une architecture REST optimisée.",
      "Réalisation d’audits de code pour identifier les axes d’amélioration en termes de performance, maintenabilité et scalabilité.",
      "Rédaction et mise à jour d’une documentation technique détaillée, facilitant l’onboarding des nouveaux développeurs et assurant la pérennité du projet.",
      "Amélioration des performances en appliquant des bonnes pratiques d’architecture et de développement.",
      "Participation aux revues de code et suivi des pull requests, garantissant le respect des standards de qualité et la cohésion technique de l’équipe.",
      "Contribution aux pratiques agiles de l’équipe (Scrum) : participation aux sprints, plannings et estimations des tâches.",
    ],
  },
  {
    id: 2,
    title: "Développeur – ReactJS & Laravel | Leptech",
    date: "Septembre 2021 - Août 2022",
    stack: ["ReactJS", "Laravel", "Docker", "Git", "REST API", "SCRUM"],
    missions: [
      "Développement d’un CRM sur mesure en collaboration avec Soliha, une entreprise à mission sociale, pour centraliser la gestion des dossiers et données des bénéficiaires.",
      "Création d’API REST robustes en Laravel avec validation avancée des données pour assurer la fiabilité et la cohérence des informations.",
      "Conception d’un tableau de bord interactif permettant un accès et un suivi simplifié des opérations en cours.",
      "Mise en place d’une gestion des rôles et permissions pour contrôler l’accès aux différentes fonctionnalités du logiciel.",
      "Gestion du cycle de vie complet des développements, de la spécification à la mise en production.",
      "Travail en équipe Agile SCRUM avec itérations courtes et feedback régulier pour améliorer l'expérience utilisateur et la performance de l'application.",
    ],
  },
  {
    id: 3,
    title: "Développeur – ReactJS & Node.js | ReadyPark",
    date: "Mars 2021 - Avril 2021 (Stage)",
    stack: ["ReactJS", "Node.js", "SCRUM"],
    missions: [
      "Développement d’une application web fullstack en React et Node.js, respectant les besoins du client et les exigences du cahier des charges.",
      "Participation aux évaluations des besoins métiers pour proposer des solutions techniques adaptées.",
      "Travail en équipe en méthodologie SCRUM, avec un focus sur l'amélioration continue et l'agilité dans le développement.",
    ],
  },
];
